# Generated by Django 3.2.15 on 2022-09-25 19:38

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220925_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(default='collectedImages/no_name300x300.jpg', upload_to=core.models.upload_to, verbose_name='Image')),
                ('width', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
                ('url', models.CharField(max_length=255)),
                ('alt', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='archivedleave',
            name='user',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profilepic',
            name='user',
        ),
        migrations.DeleteModel(
            name='AnnualLimit',
        ),
        migrations.DeleteModel(
            name='ArchivedLeave',
        ),
        migrations.DeleteModel(
            name='Leave',
        ),
        migrations.DeleteModel(
            name='ProfilePic',
        ),
    ]
